### ISSUE TITLE
Inhalt des VZ img

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/homepage-2.0-content#1]
Gehört der Inhalt des Verzeichnisses `img` wirklich in dieses Repo? Ich würde die folgenden Dateien eher dem theme-repo zuordnen:

apple-touch-icon-120x120.png
apple-touch-icon-152x152.png
apple-touch-icon-60x60.png
apple-touch-icon-76x76.png
favicon.ico
navlogo.svg
pdf.png
site.svg
sitelogo.png
sitelogo.svg

**Comment by horazont** [comment]
Könnte man auch in -theme packen. PRs welcome.

Notiz: Die Änderung müsste lokal getestet werden da Theme-Änderungen mit staging nicht funktionieren. Staging verwendet immer die selbe Theme wie die Hauptwebseite.

**Comment by horazont** [comment]
pdf.png gehört finde ich eher hierher, da wird explizit aus dem Content heraus verlinken. Der Rest ist wahrscheinlich eher theme.

**Comment by cknoll** [comment]
inhaltlich :+1:
Ist mir im Moment, aber gerade nicht wichtig genug..
