### ISSUE TITLE
Bilder gesucht

### ISSUE THREAD

**Issue by s72785** [fsfw-dresden/homepage-2.0-content#5]
Gesucht wären Bilder für unsere Artikel, die das Textbild etwas auflockern.

Vorschläge für CLT-Artikel:

* Gebäude: https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chemnitz-TU-Orangerie2008.jpg/1024px-Chemnitz-TU-Orangerie2008.jpg
* Draufsucht: https://upload.wikimedia.org/wikipedia/commons/7/74/Linux_day_Chemnitz_2011_03_%28aka%29.jpg
* Logo ohne Jahreszahl: https://media.c3d2.de/u/vv01f/m/clt-logo-farbig/
* Chaos-Stand an dem Flyer der FSFW auslagen: https://media.c3d2.de/u/vv01f/m/ccc-in-sachsen/

Weitere Vorschläge?

**Comment by horazont** [comment]
Die Draufsicht wäre mein Favorit, wenn das Lizenztechnisch hinhaut.

Folgende Gegenargumente für die anderen:

* Gebäude und Chaos-Stand: Fotoqualität überzeugt mich nicht.
* Logo ohne Jahreszahl: Langweilig.

**Comment by s72785** [comment]
Artikel in dem die Draufsicht verwendet wurde: https://de.wikipedia.org/wiki/Wikipedia:Chemnitzer_Linuxtage_2011 – Lizenz ist CC BY-SA 2.5 (us)

Dort sind auch weitere Bilder aufgeführt.

**Comment by horazont** [comment]
Ist jetzt auch egal *schließ*
